pip install streamlit 
pip install pypdf2 
pip install langchain 
pip install python-dotenv 
pip install faiss-cpu 
pip install openai 
pip install huggingface_hub
pip install tiktoken
pip install InstructorEmbedding
pip install sentence_transformers
pip install qdrant_client
